<a href="https://colab.research.google.com/github/KPaul0960/Kanish/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numerical Python**

In [4]:
import numpy as np

## Differences in python

In [ ]:
a=np.array([1,2,3],dtype='int32')
b=np.array([1,2,3])
d=a*b
print(d)

[1 4 9]


In [ ]:
c=np.array([[9.0,8.0,7.0],[1,2,3]])
print(c)

[[9. 8. 7.]
 [1. 2. 3.]]


## Getting started

In [ ]:
# Get dimension
c.ndim

2

In [ ]:
# Get shape
b.shape

(3,)

In [ ]:
#get data type
a.dtype

dtype('int32')

In [ ]:
#get size
c.itemsize

8

In [ ]:
#get total size
a.nbytes

12

In [ ]:
#get specific element
print(c[1,-2])
print(c[1,1])

2.0
2.0


In [ ]:
#get a specific row
c[0,:]

array([9., 8., 7.])

In [ ]:
#get a specific column
c[:,1]

array([8., 2.])

In [ ]:
#getting a little more freaky(startingindex:endingindex:stepsize)
c[0,0:2:1]

array([9., 8.])

In [ ]:
#mutation
c[1,2]=20
print(c)
c[:,2]=[66,33]
print(c)

[[ 9.  8.  7.]
 [ 1.  2. 20.]]
[[ 9.  8. 66.]
 [ 1.  2. 33.]]


In [ ]:
k=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(k)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#get a particular element
k[1,0,1]

6

In [ ]:
#replace
k[:,1,:]=[[9,9],[8,8]]
print(k)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing differnt types of array      

In [ ]:
#all 0s matix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [ ]:
#all 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
#identity matrix
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#any other number
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
#any other number
np.full_like(c,4)


array([[4., 4., 4.],
       [4., 4., 4.]])

In [ ]:
#random decimal
np.random.rand(2,2)
np.random.random_sample(c.shape)

array([[7.87861739e-01, 3.00827459e-01, 3.22835268e-04],
       [7.12789850e-01, 8.04964288e-01, 7.71429236e-01]])

In [ ]:
np.random.randint(4,8,size=(3,3))

array([[6, 5, 7],
       [5, 6, 4],
       [4, 4, 7]])

In [ ]:
#repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,10,axis=1)
print(r1)

[[1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3]]


In [ ]:
p=np.ones((5,5))
p[1:4,1:4]=0
p[2,2]=9
print(p)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a=np.array([1,2,3])
b=a.copy()#without this error will happen
b[0]=100
print(a)
b=a
b[0]=100
print(a)

[1 2 3]
[100   2   3]


In [9]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a**2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [ ]:
b=np.array([1,0,1,0])
print(a+b)

[2 2 4 4]


In [ ]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [ ]:
a=np.random.randint(40,60,size=(5,5))
print(a)

[[47 40 59 57 49]
 [54 41 51 57 58]
 [49 58 59 54 47]
 [41 58 58 55 57]
 [51 47 47 52 45]]


In [ ]:
a>50 #same can be done with files like txt

array([[False, False,  True,  True, False],
       [ True, False,  True,  True,  True],
       [False,  True,  True,  True, False],
       [False,  True,  True,  True,  True],
       [ True, False, False,  True, False]])

In [ ]:
a[a>50]

array([59, 57, 54, 51, 57, 58, 58, 59, 54, 58, 58, 55, 57, 51, 52])

In [5]:
# Create an empty array with 2 elements
np.empty(2)

array([-2.00000000e+000,  6.95280807e-310])

In [6]:
#arrange an element for a certain range of array
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
#create an array with values that are spaced linearly in a specified interval
np.linspace(0,3,num=5)

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

In [10]:
t=np.array([7,2,4,8,6,2,7,3])
np.sort(t)
#indirect sort along a specified axis: argsort()
#indirect stable sort on multiple keys: lexsort()
#find elements in a sorted array : searchsorted()
#partial sort : partition()

array([2, 2, 3, 4, 6, 7, 7, 8])

In [12]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(np.vstack([a,b]))
print(np.hstack([a,b]))
print(np.column_stack([a,b]))
print(a+b)
np.concatenate((a,b))

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[ 6  8 10 12]


array([1, 2, 3, 4, 5, 6, 7, 8])